### ISSUE TITLE
Warning...

### ISSUE THREAD

**Issue by aerograf** [XoopsModules25x/extgallery#12]
On PHP7, there was such a message from the plugin:

`Parameter 1 to MytsGallery::load() expected to be a reference, value given в файле /class/module.textsanitizer.php строка 770`

**Comment by mambax7** [comment]
Can you check if the issue still exist in this release? If not, could you close the issue?
https://github.com/XoopsModules25x/extgallery/releases/tag/1.14_Beta-2

**Comment by aerograf** [comment]
Ok
