### ISSUE TITLE
ExtgalleryPublicPermHandler

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/extgallery#3]
After install, when I go to modules/extgallery/admin/index.php, I get this error:
Unknown: Non-static method ExtgalleryPublicPermHandler::getHandler() should not be called statically, assuming $this from incompatible context in file /modules/extgallery/xoops_version.php line 57

and when I go on user side (/modules/extgallery/), I get this error:
Unknown: Non-static method ExtgalleryPublicPermHandler::getHandler() should not be called statically, assuming $this from incompatible context in file /modules/extgallery/class/publiccat.php line 106

___

My config:

PHP version: 5.6.4-4ubuntu6.2
MYSQL version: 5.6.25-0ubuntu0.15.04.1
XOOPS version: 2.5.7.1

**Comment by mambax7** [comment]
fixed in: https://github.com/mambax7/extgallery/commit/a538cd46733738bd5fc1df79189a8a4742507d20
